/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aips;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("It must has exactly one parameter for the input file path");
            return;
        }
        TrafficProcessor processor = new TrafficProcessor();
        TrafficFileReader reader;
        reader = new TrafficFileReader(new File(args[0]));
        while(reader.hasNext()) {
            processor.addSlotTraffic(reader.next());
        }
        reader.close();
        System.out.println(processor.getTotalCount());
        Map<LocalDate, Long> dailyTraffic = processor.getDailyCounts();
        for (Map.Entry<LocalDate, Long> entry: dailyTraffic.entrySet()) {
            System.out.println(entry.getKey() + " " + entry.getValue());
        }
        List<LocalDateTime> slotsWithMostTraffic =  processor.getSlotsWithMostTraffic();
        for (LocalDateTime slots: slotsWithMostTraffic) {
            System.out.println(slots);
        }
        List<LocalDateTime> threeContiguousSlotsWithLeastTraffic =  processor.getThreeContiguousSlotsWithLeastTraffic();
        for (LocalDateTime slots: threeContiguousSlotsWithLeastTraffic) {
            System.out.println(slots);
        }

    }
}
